#!/usr/bin/env python3
"""Build a public-only, dependency-free static artifact. Never publish the repo root."""
from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urljoin, urlparse, unquote
import hashlib
import json
import re
import shutil

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / '_site'
MARKER = OUTPUT / '.lchaim-build'
ORIGIN = 'https://lchaimlyrics.com/'


class Assets(HTMLParser):
    def __init__(self):
        super().__init__()
        self.urls = set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        for key in ('src', 'data-audio'):
            if attrs.get(key):
                self.urls.add(attrs[key])
        if tag == 'link' and attrs.get('href'):
            self.urls.add(attrs['href'])


def build():
    pages = json.loads((ROOT / 'config/public-pages.json').read_text())
    pricing = json.loads((ROOT / 'config/packages.json').read_text())
    if OUTPUT.exists():
        if not MARKER.is_file() or MARKER.read_text() != 'Generated by scripts/build-site.py\n':
            raise SystemExit('Refusing to replace an unrecognized _site directory.')
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir()
    MARKER.write_text('Generated by scripts/build-site.py\n')
    assets = set()
    for page in pages:
        source = ROOT / page
        html = source.read_text()

        def price_block(match):
            key = match.group(1)
            price = pricing['packages'][key]['price']
            return (f'<!-- package-price:{key} -->\n'
                    f'                    <p class="price"><span class="amount">${price}</span> '
                    f'<span>{pricing["currency"]} · one-time</span></p>\n'
                    '                    <!-- /package-price -->')

        html = re.sub(r'<!-- package-price:([a-z-]+) -->.*?<!-- /package-price -->', price_block, html, flags=re.S)
        lowest = min(plan['price'] for plan in pricing['packages'].values())
        html = re.sub(r'Packages from \$\d+ USD\.', f'Packages from ${lowest} {pricing["currency"]}.', html)
        # Content-derived cache versions avoid old CSS/JS after a release.
        def version_asset(match):
            prefix, relpath = match.group(1), match.group(2)
            path = ROOT / relpath
            version = hashlib.sha256(path.read_bytes()).hexdigest()[:12]
            return f'{prefix}{relpath}?v={version}'
        html = re.sub(r'((?:\.\./)?)(css/styles\.css|js/(?:main|languages)\.js)(?:\?[^"\s]*)?', version_asset, html)
        parsed = Assets()
        parsed.feed(html)
        for url in parsed.urls:
            resolved = urlparse(urljoin(ORIGIN + page, url))
            if resolved.netloc == 'lchaimlyrics.com':
                rel = unquote(resolved.path).lstrip('/')
                if rel.startswith(('assets/', 'css/', 'js/')):
                    assets.add(rel)
        target = OUTPUT / page
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(html)
    public_files = assets | {'robots.txt', 'sitemap.xml', 'CNAME', 'favicon.ico',
                            'yandex_702d363d880036ae.html', 'd79f5111c7c09510f3352bee617ffae7.txt'}
    for rel in sorted(public_files):
        source = ROOT / rel
        if not source.is_file() or not source.resolve().is_relative_to(ROOT):
            raise SystemExit(f'Missing or unsafe public file: {rel}')
        target = OUTPUT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    print(f'Built {len(pages)} pages and {len(public_files)} public assets into _site/')


if __name__ == '__main__':
    build()
